/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardChildrenRouteImport } from './routes/dashboard.children'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChildrenRoute = DashboardChildrenRouteImport.update({
  id: '/dashboard/children',
  path: '/dashboard/children',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/inventory': typeof InventoryRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/dashboard/children': typeof DashboardChildrenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/inventory': typeof InventoryRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/dashboard/children': typeof DashboardChildrenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/inventory': typeof InventoryRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/dashboard/children': typeof DashboardChildrenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/documents'
    | '/donations'
    | '/events'
    | '/inventory'
    | '/reports'
    | '/staff'
    | '/dashboard/children'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/documents'
    | '/donations'
    | '/events'
    | '/inventory'
    | '/reports'
    | '/staff'
    | '/dashboard/children'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/documents'
    | '/donations'
    | '/events'
    | '/inventory'
    | '/reports'
    | '/staff'
    | '/dashboard/children'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  DocumentsRoute: typeof DocumentsRoute
  DonationsRoute: typeof DonationsRoute
  EventsRoute: typeof EventsRoute
  InventoryRoute: typeof InventoryRoute
  ReportsRoute: typeof ReportsRoute
  StaffRoute: typeof StaffRoute
  DashboardChildrenRoute: typeof DashboardChildrenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/children': {
      id: '/dashboard/children'
      path: '/dashboard/children'
      fullPath: '/dashboard/children'
      preLoaderRoute: typeof DashboardChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  DocumentsRoute: DocumentsRoute,
  DonationsRoute: DonationsRoute,
  EventsRoute: EventsRoute,
  InventoryRoute: InventoryRoute,
  ReportsRoute: ReportsRoute,
  StaffRoute: StaffRoute,
  DashboardChildrenRoute: DashboardChildrenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
