/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardDonationsRouteImport } from './routes/dashboard.donations'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as DashboardChildrenRouteImport } from './routes/dashboard.children'

const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/dashboard/staff',
  path: '/dashboard/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/dashboard/inventory',
  path: '/dashboard/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/dashboard/events',
  path: '/dashboard/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDonationsRoute = DashboardDonationsRouteImport.update({
  id: '/dashboard/donations',
  path: '/dashboard/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/dashboard/documents',
  path: '/dashboard/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/dashboard/compliance',
  path: '/dashboard/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChildrenRoute = DashboardChildrenRouteImport.update({
  id: '/dashboard/children',
  path: '/dashboard/children',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard/children': typeof DashboardChildrenRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard/children': typeof DashboardChildrenRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard/children': typeof DashboardChildrenRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard/children'
    | '/dashboard/compliance'
    | '/dashboard/documents'
    | '/dashboard/donations'
    | '/dashboard/events'
    | '/dashboard/inventory'
    | '/dashboard/reports'
    | '/dashboard/staff'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard/children'
    | '/dashboard/compliance'
    | '/dashboard/documents'
    | '/dashboard/donations'
    | '/dashboard/events'
    | '/dashboard/inventory'
    | '/dashboard/reports'
    | '/dashboard/staff'
    | '/dashboard'
  id:
    | '__root__'
    | '/dashboard/children'
    | '/dashboard/compliance'
    | '/dashboard/documents'
    | '/dashboard/donations'
    | '/dashboard/events'
    | '/dashboard/inventory'
    | '/dashboard/reports'
    | '/dashboard/staff'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardChildrenRoute: typeof DashboardChildrenRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardDonationsRoute: typeof DashboardDonationsRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/dashboard/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/dashboard/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/dashboard/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/donations': {
      id: '/dashboard/donations'
      path: '/dashboard/donations'
      fullPath: '/dashboard/donations'
      preLoaderRoute: typeof DashboardDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/dashboard/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/dashboard/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/children': {
      id: '/dashboard/children'
      path: '/dashboard/children'
      fullPath: '/dashboard/children'
      preLoaderRoute: typeof DashboardChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardChildrenRoute: DashboardChildrenRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardDonationsRoute: DashboardDonationsRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
